### PR TITLE
finished

### PR DESCRIPTION
**Pull request by Tile561**
finished the coding assignment

### CODE REVIEW

**Comment by mikeshanahan** [comment]
@Tile561 Hi James, thanks for the submission. Please take a crack at creating a test for the article that works without an internet connection. It can be a little tricky but there is a solution using the native unittest library

**Comment by Tile561** [comment]
> @Tile561 Hi James, thanks for the submission. Please take a crack at creating a test for the article that works without an internet connection. It can be a little tricky but there is a solution using the native unittest library

it works without wifi now

**Comment by mikeshanahan** [comment]
> > @Tile561 Hi James, thanks for the submission. Please take a crack at creating a test for the article that works without an internet connection. It can be a little tricky but there is a solution using the native unittest library
> 
> it works without wifi now

Can you send me the link to the updated code? I'm not seeing any updates to the PR

**Comment by Tile561** [comment]
> > > @Tile561 Hi James, thanks for the submission. Please take a crack at creating a test for the article that works without an internet connection. It can be a little tricky but there is a solution using the native unittest library
> > 
> > 
> > it works without wifi now
> 
> Can you send me the link to the updated code? I'm not seeing any updates to the PR

Oh sorry, 
https://github.com/Tile561/candidate-challenge/tree/challengeSubmission/Merilien

**Pull request closed without merging**
